const VERSION='pichat-v3-3500';
const SHELL_CACHE=`${VERSION}-shell`;
const RUNTIME_CACHE=`${VERSION}-runtime`;
// 3.5 PERFORMANCE : shell volontairement petit. Les gros modules sont mis en
// cache à la demande au lieu de bloquer l'installation de la PWA.
const CORE_SHELL=[
  '/offline.html','/manifest.webmanifest',
  '/css/brand35.css?v=3500','/css/pwa.css?v=3500','/css/chat35.bundle.css?v=3500','/css/admin35.bundle.css?v=3500',
  '/js/brand35.js?v=3500','/js/performance35.js?v=3500','/js/pwa.js?v=3500','/js/chat35.bundle.js?v=3500','/js/admin35.bundle.js?v=3500',
  '/assets/icons/pichat-192.png','/assets/icons/pichat-512.png','/assets/brand/pichat-mascot.svg?v=3500'
];
self.addEventListener('install',event=>{event.waitUntil(caches.open(SHELL_CACHE).then(c=>c.addAll(CORE_SHELL)).catch(()=>null));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>![SHELL_CACHE,RUNTIME_CACHE].includes(k)).map(k=>caches.delete(k)));await self.clients.claim();const list=await self.clients.matchAll({type:'window',includeUncontrolled:true});list.forEach(c=>c.postMessage({type:'PICHAT_UPDATED',version:'3.5.0'}))})())});
async function networkFirst(req,fallback){try{const fresh=await fetch(req,{cache:'no-store'});if(fresh.ok){const c=await caches.open(RUNTIME_CACHE);c.put(req,fresh.clone())}return fresh}catch(_){return(await caches.match(req))||(fallback?await caches.match(fallback):Response.error())}}
async function cacheFirstVersioned(req){const cached=await caches.match(req);if(cached)return cached;try{const fresh=await fetch(req);if(fresh.ok){const c=await caches.open(RUNTIME_CACHE);await c.put(req,fresh.clone())}return fresh}catch(_){return Response.error()}}
async function staleWhileRevalidate(req){const cached=await caches.match(req);const refresh=fetch(req).then(async fresh=>{if(fresh.ok){const c=await caches.open(RUNTIME_CACHE);await c.put(req,fresh.clone())}return fresh}).catch(()=>null);return cached||await refresh||Response.error()}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/ws')||url.pathname.startsWith('/uploads/'))return;if(req.mode==='navigate'){event.respondWith(networkFirst(req,'/offline.html'));return}if((url.pathname.startsWith('/css/')||url.pathname.startsWith('/js/')||url.pathname.startsWith('/assets/'))&&url.searchParams.get('v')==='3500'){event.respondWith(cacheFirstVersioned(req));return}if(['style','script','manifest'].includes(req.destination)){event.respondWith(networkFirst(req));return}if(req.destination==='image'||req.destination==='font'){event.respondWith(staleWhileRevalidate(req))}});
self.addEventListener('notificationclick',event=>{event.notification.close();const target=event.notification.data?.url||'/';event.waitUntil((async()=>{const windows=await clients.matchAll({type:'window',includeUncontrolled:true});for(const client of windows){if('focus'in client){await client.focus();client.postMessage({type:'pichat:notification-click',roomId:event.notification.data?.roomId||null});return}}if(clients.openWindow)await clients.openWindow(target)})())});
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting();if(event.data?.type==='CHECK_UPDATE')event.waitUntil(self.registration.update());if(event.data?.type==='SHOW_NOTIFICATION'){const d=event.data.payload||{};event.waitUntil(self.registration.showNotification(d.title||'PiChat',{body:d.body||'Nouveau message',icon:'/assets/icons/pichat-192.png',badge:'/assets/icons/pichat-96.png',tag:d.tag||`pichat-${Date.now()}`,renotify:true,silent:!!d.silent,data:{url:d.url||'/',roomId:d.roomId||null}}))}});
