"""Copie le dossier _template, renomme-le, puis modifie seulement ce dictionnaire."""
FIGHTER = {
    "id": "mon_perso",
    "name": "Mon Perso",
    "title": "Nouveau combattant",
    "description": "Description du combattant.",
    "rarity": "Community",
    "color": "#7c83ff",
    "stats": {"max_hp": 4000, "speed": 250, "radius": 30, "ammo": 3, "reload_ms": 1400},
    "attack": {
        "type": "spread_shot",
        "name": "Attaque principale",
        "damage": 260,
        "range": 500,
        "projectile_speed": 950,
        "pellets": 4,
        "spread_deg": 24,
        "cooldown_ms": 400,
        "projectile_radius": 7,
    },
    "super": {
        "type": "super_spread",
        "name": "Super",
        "damage": 230,
        "range": 650,
        "projectile_speed": 1100,
        "pellets": 8,
        "spread_deg": 44,
        "cooldown_ms": 700,
        "projectile_radius": 9,
        "knockback": 180,
        "charge_hits": 8,
    },
}
