(()=>{
  const $=id=>document.getElementById(id);let data=null;
  const names={reflex:'⚡ Réflexe éclair',memory:'🧠 Mémoire express',clicker:'👆 Click Rush',number:'🔢 Nombre mystère',quiz:'🧩 Quiz express',tictactoe:'⭕ Morpion'};
  async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'Erreur Arcade');return d}
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function notice(text,ok=true){if(window.msg)return window.msg(text,ok);alert(text)}
  async function load(){if(!$('arcade-admin-form'))return;try{data=await api('/api/admin/arcade');render()}catch(e){notice(e.message,false)}}
  function render(){const s=data.settings,t=data.totals;$('arcade-admin-enabled').checked=!!s.enabled;$('arcade-admin-rewards').checked=!!s.rewards_enabled;$('arcade-admin-plays').value=s.rewarded_plays_per_day;$('arcade-admin-cap').value=s.daily_coin_cap;$('arcade-admin-daily-coins').value=s.daily_challenge_coins;$('arcade-admin-daily-xp').value=s.daily_challenge_xp;$('arcade-admin-totals').innerHTML=[['Parties',t.plays],['Joueurs',t.players],['PyCoins distribués',t.coins],['XP distribuée',t.xp]].map(x=>`<div class="arcade-admin-total"><b>${Number(x[1]||0)}</b><small>${x[0]}</small></div>`).join('');$('arcade-admin-popular').innerHTML=data.popular.length?data.popular.map(x=>`<div class="arcade-admin-row"><span>${names[x.game_key]||esc(x.game_key)}</span><b>${x.plays}</b></div>`).join(''):'<p class="muted">Aucune partie.</p>';$('arcade-admin-recent').innerHTML=data.recent.length?data.recent.map(x=>`<div class="arcade-admin-row"><span><b>${esc(x.username)}</b><br><small>${names[x.game_key]||esc(x.game_key)} · ${esc(x.result_label)} · ${esc(x.created_at)}</small></span><b>${x.score}</b></div>`).join(''):'<p class="muted">Aucune partie.</p>'}
  async function save(e){e.preventDefault();try{const settings=await api('/api/admin/arcade/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:$('arcade-admin-enabled').checked,rewards_enabled:$('arcade-admin-rewards').checked,rewarded_plays_per_day:Number($('arcade-admin-plays').value),daily_coin_cap:Number($('arcade-admin-cap').value),daily_challenge_coins:Number($('arcade-admin-daily-coins').value),daily_challenge_xp:Number($('arcade-admin-daily-xp').value)})});data.settings=settings;render();notice('Réglages Arcade enregistrés.',true)}catch(error){notice(error.message,false)}}
  $('arcade-admin-form')?.addEventListener('submit',save);$('arcade-admin-refresh')?.addEventListener('click',load);document.querySelector('[data-tab="arcade"]')?.addEventListener('click',load);load();
})();
