(()=>{
const $=id=>document.getElementById(id);let backups=[],selected=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>{const u=['o','Ko','Mo','Go'];let i=0,v=Number(n||0);while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`};
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',...opt});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.detail||`Erreur ${r.status}`);return d}
function notify(t,ok=false){if(window.msg)return window.msg(t,ok);alert(t)}
async function load(){const list=$('backup-list');if(!list)return;try{backups=await api('/api/admin/backups');renderList();if(selected){const same=backups.find(x=>x.name===selected.name);if(same)await select(same.name);else{selected=null;renderEmpty()}}}catch(e){list.innerHTML=`<p class="backup-error">${esc(e.message)}</p>`}}
function renderList(){const el=$('backup-list');if(!backups.length){el.innerHTML='<div class="backup-empty compact"><span>💾</span><strong>Aucun backup</strong><small>Crée ton premier backup avec le bouton ci-dessus.</small></div>';return}el.innerHTML=backups.map(b=>`<button class="backup-card ${selected?.name===b.name?'active':''} ${b.valid?'':'invalid'}" data-backup="${esc(b.name)}"><span class="backup-card-icon">${b.valid?'💾':'⚠️'}</span><span><strong>${esc(b.label||b.name)}</strong><small>${esc(b.name)}</small><small>${b.valid?`${b.users} comptes · ${b.messages} messages · ${fmt(b.size)}`:esc(b.error)}</small></span><time>${esc((b.created_at||b.modified_at||'').replace('T',' ').slice(0,16))}</time></button>`).join('');el.querySelectorAll('[data-backup]').forEach(b=>b.onclick=()=>select(b.dataset.backup))}
function renderEmpty(){$('backup-detail').innerHTML='<div class="backup-empty"><span>💾</span><strong>Sélectionne une sauvegarde</strong><small>Son contenu et ses outils apparaîtront ici.</small></div>'}
async function select(name){try{selected=await api('/api/admin/backups/'+encodeURIComponent(name));renderList();renderDetail()}catch(e){notify(e.message)}}
function renderDetail(){const b=selected, el=$('backup-detail');if(!b)return renderEmpty();const files=b.files||[];el.innerHTML=`<div class="backup-detail-head"><div><span class="state-badge ${b.valid?'state-active':'state-banned'}">${b.valid?'VALIDE':'INVALIDE'}</span><h3>${esc(b.label||b.name)}</h3><p>${esc(b.name)}</p></div><a class="mini brand" href="/api/admin/backups/${encodeURIComponent(b.name)}/download">Télécharger</a></div><div class="backup-metrics"><div><b>${b.users}</b><small>COMPTES</small></div><div><b>${b.rooms}</b><small>SALONS</small></div><div><b>${b.messages}</b><small>MESSAGES</small></div><div><b>${b.uploads}</b><small>FICHIERS</small></div></div><label>Étiquette<input id="backup-label" maxlength="100" value="${esc(b.label||'')}"></label><label>Note<textarea id="backup-note" rows="3" maxlength="500">${esc(b.note||'')}</textarea></label><button id="backup-save-meta" class="primary-action">Enregistrer l’étiquette et la note</button><div class="backup-actions"><button data-ba="validate" class="mini good">✓ Vérifier</button><button data-ba="rename" class="mini">Renommer</button><button data-ba="duplicate" class="mini">Dupliquer</button><a class="mini" href="/api/admin/backups/${encodeURIComponent(b.name)}/accounts.csv">Comptes CSV</a><button data-ba="restore" class="mini bad">Restaurer</button><button data-ba="delete" class="mini bad">Supprimer</button></div><div class="backup-files-head"><div><h4>Fichiers inclus</h4><small>Tu peux ajouter, remplacer, extraire ou retirer un fichier du dossier uploads.</small></div><button id="backup-add-file" class="mini brand">＋ Ajouter</button><input id="backup-add-file-input" type="file" hidden></div><div class="backup-files">${files.length?files.map(f=>`<div class="backup-file"><span>📎</span><span><strong>${esc(f.name||f.path.replace(/^uploads\//,''))}</strong><small>${fmt(f.size)}</small></span><a title="Extraire" href="/api/admin/backups/${encodeURIComponent(b.name)}/files/${encodeURIComponent(f.path.replace(/^uploads\//,''))}">↓</a><button title="Retirer" data-remove-file="${esc(f.path)}">×</button></div>`).join(''):'<p class="muted">Aucun fichier uploadé dans ce backup.</p>'}</div>`;
$('backup-save-meta').onclick=saveMeta;el.querySelectorAll('[data-ba]').forEach(x=>x.onclick=()=>action(x.dataset.ba));$('backup-add-file').onclick=()=>$('backup-add-file-input').click();$('backup-add-file-input').onchange=addFile;el.querySelectorAll('[data-remove-file]').forEach(x=>x.onclick=()=>removeFile(x.dataset.removeFile));}
async function saveMeta(){try{selected=await api('/api/admin/backups/'+encodeURIComponent(selected.name),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:$('backup-label').value,note:$('backup-note').value})});notify('Backup modifié.',true);await load()}catch(e){notify(e.message)}}
async function action(a){if(!selected)return;try{if(a==='validate'){await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/validate`,{method:'POST'});notify('Backup valide ✓',true)}if(a==='rename'){const n=prompt('Nouveau nom du fichier ZIP :',selected.name);if(!n)return;selected=await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/rename`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_name:n})});notify('Backup renommé.',true)}if(a==='duplicate'){const n=prompt('Nom de la copie (laisser vide pour automatique) :','');selected=await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/duplicate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_name:n||null})});notify('Copie créée.',true)}if(a==='delete'){if(!confirm(`Supprimer définitivement ${selected.name} ?`))return;await api(`/api/admin/backups/${encodeURIComponent(selected.name)}`,{method:'DELETE'});selected=null;notify('Backup supprimé.',true)}if(a==='restore'){const c=prompt(`RESTAURATION COMPLÈTE\n\nPiChat créera d’abord une sauvegarde de sécurité. Tous les utilisateurs seront déconnectés.\n\nTape RESTAURER pour continuer :`,'');if(c!=='RESTAURER')return;const r=await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/restore`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:c})});alert(`Restauration terminée.\nBackup de sécurité : ${r.safety_backup}\n\nRecharge PiChat et reconnecte-toi.`);location.href='/login';return}await load()}catch(e){notify(e.message)}}
async function create(){const label=prompt('Étiquette du nouveau backup (facultatif) :','Backup manuel');if(label===null)return;try{selected=await api('/api/admin/backups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label,note:''})});notify('Backup créé ✓',true);await load()}catch(e){notify(e.message)}}
async function importZip(){const input=$('backup-import-file'),file=input.files[0];if(!file)return;const fd=new FormData();fd.append('file',file);try{selected=await api('/api/admin/backups/import',{method:'POST',body:fd});notify('Backup importé ✓',true);await load()}catch(e){notify(e.message)}finally{input.value=''}}
async function addFile(){const input=$('backup-add-file-input'),file=input.files[0];if(!file)return;const fd=new FormData();fd.append('file',file);try{selected=await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/files`,{method:'POST',body:fd});notify('Fichier ajouté au backup.',true);await load()}catch(e){notify(e.message)}finally{input.value=''}}
async function removeFile(path){if(!confirm(`Retirer ${path.replace(/^uploads\//,'')} de ce backup ?`))return;try{selected=await api(`/api/admin/backups/${encodeURIComponent(selected.name)}/files`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});notify('Fichier retiré.',true);await load()}catch(e){notify(e.message)}}
function bind(){if(!$('backup-list'))return;$('backup-create').onclick=create;$('backup-import').onclick=()=>$('backup-import-file').click();$('backup-import-file').onchange=importZip;load();window.addEventListener('hashchange',()=>{if(location.hash==='#backups')load()})}
document.addEventListener('DOMContentLoaded',bind);window.PiChatBackupStudio={load};})();
