const $=id=>document.getElementById(id);let me=null,users=[],rooms=[],reports=[],actions=[],activeNoteUser=null;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(url,opt={}){const r=await fetch(url,opt);if(r.status===401){location.href='/login';throw Error('Connexion requise')}let d=null;try{d=await r.json()}catch{}if(!r.ok)throw Error(d?.detail||`Erreur ${r.status}`);return d}function toast(t,ok=false){const el=$(ok?'success-message':'error-message');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}function post(url,data){return api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})})}function patch(url,data){return api(url,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data||{})})}
document.addEventListener('DOMContentLoaded',init);async function init(){try{me=await api('/api/me');if(!me.is_admin&&!me.is_moderator){location.href='/';return}$('admin-link').style.display=me.is_admin?'':'none';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=me.is_admin?'':'none');$('mod-title').textContent=me.is_admin?'Modération globale':`Modération ${me.moderator_class_code}`;$('mod-scope').textContent=me.is_admin?'Tous les serveurs et toutes les classes.':`Pouvoirs limités aux joueurs et salons ${me.moderator_class_code}. Tu peux parler dans Général sans le modérer.`;bind();await refreshAll()}catch(e){toast(e.message)}}function bind(){document.querySelectorAll('.mod-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mod-tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.mod-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab))});$('refresh-all').onclick=refreshAll;$('report-status').onchange=loadReports;$('member-search').oninput=renderUsers;$('settings-form').onsubmit=saveSettings;$('save-note').onclick=saveNote}
async function refreshAll(){try{await Promise.all([loadUsers(),loadRooms(),loadReports(),loadActions(),me.is_admin?loadSettings():Promise.resolve()]);stats()}catch(e){toast(e.message)}}function stats(){$('stat-reports').textContent=reports.filter(x=>x.status==='open').length;$('stat-users').textContent=users.filter(x=>!x.is_bot).length;$('stat-muted').textContent=users.filter(x=>x.is_muted).length;$('stat-actions').textContent=actions.length}
async function loadUsers(){users=await api('/api/moderation/users');for(const u of users){try{const r=await api(`/api/moderation/restrictions/${u.id}`);Object.assign(u,r)}catch{}}renderUsers()}function renderUsers(){const q=$('member-search').value.trim().toLowerCase(),box=$('members-list');const xs=users.filter(u=>!u.is_bot&&u.id!==me.id&&u.username.toLowerCase().includes(q));box.innerHTML=xs.length?'':'<p class="muted">Aucun membre.</p>';xs.forEach(u=>{const c=document.createElement('article');c.className='member-card';c.innerHTML=`<div class="member-head"><div><strong>${esc(u.username)}</strong><div class="member-meta"><span>${esc(u.class_code||'Sans classe')}</span><span>${u.is_admin?'ADMIN':u.is_moderator?'MODO':'JOUEUR'}</span><span>⚠ ${u.warning_count||0}</span></div></div><span class="status-pill">${u.is_banned?'Banni':u.is_muted?'Muet jusqu’au '+esc(u.muted_until):'Actif'}</span></div><div class="actions"></div>`;const a=c.querySelector('.actions');a.append(button('Avertir','warn',()=>warn(u)),button('Mute','warn',()=>mute(u)),button('Ban temporaire','danger',()=>tempBan(u)),button('Notes','',()=>openNotes(u)));if(u.is_muted)a.append(button('Démute','good',()=>unmute(u)));box.append(c)})}function button(label,cls,fn){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;return b}async function warn(u){const reason=prompt(`Motif de l’avertissement pour ${u.username}:`,'Non-respect du règlement');if(reason===null)return;try{await post(`/api/moderation/users/${u.id}/warn`,{reason});toast('Avertissement envoyé.',true);await refreshAll()}catch(e){toast(e.message)}}async function mute(u){const minutes=Number(prompt('Durée du mute en minutes :','10'));if(!minutes)return;const reason=prompt('Motif :','Spam ou comportement inadapté');if(reason===null)return;try{await post(`/api/moderation/users/${u.id}/mute`,{duration_minutes:minutes,reason});toast('Utilisateur mis en mode muet.',true);await refreshAll()}catch(e){toast(e.message)}}async function unmute(u){try{await post(`/api/moderation/users/${u.id}/unmute`,{});toast('Mute levé.',true);await refreshAll()}catch(e){toast(e.message)}}async function tempBan(u){const minutes=Number(prompt('Durée du ban temporaire en minutes :','60'));if(!minutes)return;const reason=prompt('Motif :','Infraction au règlement');if(reason===null)return;try{await post(`/api/moderation/users/${u.id}/temporary-ban`,{duration_minutes:minutes,reason});toast('Ban temporaire appliqué.',true);await refreshAll()}catch(e){toast(e.message)}}
async function openNotes(u){activeNoteUser=u;$('notes-title').textContent='Notes privées — '+u.username;$('note-input').value='';try{const ns=await api(`/api/moderation/users/${u.id}/notes`);$('notes-list').innerHTML=ns.length?ns.map(n=>`<div class="note-item"><strong>${esc(n.author||'système')}</strong><div>${esc(n.note)}</div><small>${esc(n.created_at)}</small></div>`).join(''):'<p class="muted">Aucune note.</p>';$('notes-dialog').showModal()}catch(e){toast(e.message)}}async function saveNote(){const note=$('note-input').value.trim();if(!note||!activeNoteUser)return;try{await post(`/api/moderation/users/${activeNoteUser.id}/notes`,{note});await openNotes(activeNoteUser);toast('Note ajoutée.',true)}catch(e){toast(e.message)}}
async function loadReports(){reports=await api(`/api/moderation/reports?status_filter=${encodeURIComponent($('report-status').value)}`);renderReports()}function renderReports(){const box=$('reports-list');box.innerHTML=reports.length?'':'<p class="muted">Aucun signalement dans cette vue.</p>';reports.forEach(r=>{const c=document.createElement('article');c.className='report-card';c.innerHTML=`<div class="report-head"><div><strong>${esc(r.author)}</strong> · ${esc(r.room_name)}</div><span class="status-pill">${esc(r.status)}</span></div><p class="meta">Signalé par ${esc(r.reporter)} — ${esc(r.created_at)} · ${esc(r.reason||'Sans motif')}</p><div class="report-message">${esc(r.content)}</div><div class="actions"></div>`;const a=c.querySelector('.actions');if(r.status==='open'){a.append(button('Résoudre','good',()=>decide(r,'resolved')),button('Rejeter','',()=>decide(r,'rejected')),button('Supprimer le message','danger',()=>deleteReported(r)),button('Sanctionner auteur','warn',()=>{const u=users.find(x=>x.id===r.author_id);if(u)mute(u)}))}box.append(c)})}async function decide(r,status){const note=prompt('Note de décision :',status==='resolved'?'Traité par la modération.':'Signalement non retenu.');if(note===null)return;try{await patch(`/api/moderation/reports/${r.id}`,{status,note});toast('Signalement mis à jour.',true);await refreshAll()}catch(e){toast(e.message)}}async function deleteReported(r){if(!confirm('Supprimer ce message et résoudre le signalement ?'))return;try{await api(`/api/moderation/reports/${r.id}/message`,{method:'DELETE'});toast('Message supprimé.',true);await refreshAll()}catch(e){toast(e.message)}}
async function loadRooms(){rooms=await api('/api/rooms');renderRooms()}function renderRooms(){const box=$('rooms-list');const xs=me.is_admin?rooms:rooms.filter(r=>r.class_code===me.moderator_class_code);box.innerHTML=xs.length?'':'<p class="muted">Aucun salon modérable.</p>';xs.forEach(r=>{const c=document.createElement('article');c.className='room-card';c.innerHTML=`<div class="room-head"><div><strong>${esc(r.name)}</strong><div class="meta">${esc(r.class_code||'Général')}</div></div><span class="status-pill">${r.slow_mode_seconds||0}s</span></div><div class="actions"></div>`;c.querySelector('.actions').append(button('Changer le mode lent','',async()=>{const sec=Number(prompt('Secondes entre deux messages (0 = désactivé) :',r.slow_mode_seconds||0));if(Number.isNaN(sec))return;try{await patch(`/api/moderation/rooms/${r.id}/slow-mode`,{seconds:sec});toast('Mode lent enregistré.',true);await loadRooms()}catch(e){toast(e.message)}}));box.append(c)})}
async function loadActions(){actions=await api('/api/moderation/actions');const b=$('actions-body');b.innerHTML=actions.length?'':'<tr><td colspan="5">Aucune action.</td></tr>';actions.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(x.created_at)}</td><td>${esc(x.actor||'système')}</td><td>${esc(x.target||'—')}</td><td>${esc(x.action)}</td><td>${esc(x.reason||x.room_name||'')}</td>`;b.append(tr)})}
async function loadSettings(){const s=await api('/api/admin/advanced-moderation-settings');$('set-profanity').checked=s.profanity_enabled;$('set-words').value=s.profanity_words;$('set-duplicate').checked=s.duplicate_enabled;$('set-duplicate-window').value=s.duplicate_window_seconds;$('set-similarity').checked=s.similarity_enabled;$('set-similarity-ratio').value=s.similarity_ratio;$('set-similarity-min').value=s.similarity_min_length;$('set-similarity-window').value=s.similarity_window_seconds;$('set-burst').checked=s.burst_enabled;$('set-burst-count').value=s.burst_count;$('set-burst-window').value=s.burst_window_seconds;$('set-rapid-count').value=s.rapid_count??3;$('set-rapid-window').value=s.rapid_window_seconds??1.8;$('set-uppercase').checked=s.uppercase_enabled;$('set-uppercase-min').value=s.uppercase_min_length;$('set-uppercase-ratio').value=s.uppercase_ratio;$('set-rate-count').value=s.rate_limit_count;$('set-rate-window').value=s.rate_limit_window_seconds;$('set-repeat-chars').value=s.repeated_char_limit;$('set-punctuation').value=s.punctuation_limit;$('set-emojis').value=s.emoji_limit;$('set-repeat-words').value=s.word_repeat_limit;$('set-cooldown-base').value=s.cooldown_base_seconds;$('set-cooldown-max').value=s.cooldown_max_seconds}async function saveSettings(e){e.preventDefault();try{await patch('/api/admin/advanced-moderation-settings',{profanity_enabled:$('set-profanity').checked,profanity_words:$('set-words').value,duplicate_enabled:$('set-duplicate').checked,duplicate_window_seconds:Number($('set-duplicate-window').value),similarity_enabled:$('set-similarity').checked,similarity_ratio:Number($('set-similarity-ratio').value),similarity_min_length:Number($('set-similarity-min').value),similarity_window_seconds:Number($('set-similarity-window').value),burst_enabled:$('set-burst').checked,burst_count:Number($('set-burst-count').value),burst_window_seconds:Number($('set-burst-window').value),rapid_count:Number($('set-rapid-count').value),rapid_window_seconds:Number($('set-rapid-window').value),uppercase_enabled:$('set-uppercase').checked,uppercase_min_length:Number($('set-uppercase-min').value),uppercase_ratio:Number($('set-uppercase-ratio').value),rate_limit_count:Number($('set-rate-count').value),rate_limit_window_seconds:Number($('set-rate-window').value),repeated_char_limit:Number($('set-repeat-chars').value),punctuation_limit:Number($('set-punctuation').value),emoji_limit:Number($('set-emojis').value),word_repeat_limit:Number($('set-repeat-words').value),cooldown_base_seconds:Number($('set-cooldown-base').value),cooldown_max_seconds:Number($('set-cooldown-max').value)});toast('Anti-spam 1.1.3 enregistré.',true)}catch(e2){toast(e2.message)}}
/* PiChat 1.1.3 — permissions de modération configurables */
function can(permission){return !!me?.is_admin || (me?.moderator_permissions||[]).includes(permission)}
function showTabPermission(tab,allowed){const b=document.querySelector(`.mod-tabs button[data-tab="${tab}"]`);if(b)b.style.display=allowed?'':'none';const p=document.querySelector(`.mod-panel[data-panel="${tab}"]`);if(p&&!allowed)p.classList.remove('active')}
function applyPermissionUI(){
  if(!me)return;
  showTabPermission('reports',can('reports_view'));
  showTabPermission('members',['users_warn','users_mute','users_tempban','users_kick','notes_manage'].some(can));
  showTabPermission('rooms',can('slowmode_manage'));
  showTabPermission('history',can('history_view'));
  const active=document.querySelector('.mod-tabs button.active:not([style*="display: none"])')||[...document.querySelectorAll('.mod-tabs button')].find(x=>x.style.display!=='none');
  if(active){document.querySelectorAll('.mod-tabs button').forEach(x=>x.classList.toggle('active',x===active));document.querySelectorAll('.mod-panel').forEach(x=>x.classList.toggle('active',x.dataset.panel===active.dataset.tab))}
  if(!me.is_admin){$('mod-scope').textContent=`Classe ${me.moderator_class_code} · ${me.moderator_permissions.length} permission(s) activée(s). Général reste accessible sans pouvoir de modération.`}
}
async function init(){try{me=await api('/api/me');if(!me.is_admin&&!me.is_moderator){location.href='/';return}$('admin-link').style.display=me.is_admin?'':'none';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=me.is_admin?'':'none');$('mod-title').textContent=me.is_admin?'Modération globale':`Modération ${me.moderator_class_code}`;bind();applyPermissionUI();await refreshAll()}catch(e){toast(e.message)}}
async function refreshAll(){
  try{
    const jobs=[];
    jobs.push(loadUsers());
    if(can('reports_view'))jobs.push(loadReports());else reports=[];
    if(can('slowmode_manage'))jobs.push(loadRooms());else rooms=[];
    if(can('history_view'))jobs.push(loadActions());else actions=[];
    if(me.is_admin)jobs.push(loadSettings());
    await Promise.all(jobs);stats();applyPermissionUI();
  }catch(e){toast(e.message)}
}
async function loadUsers(){
  users=await api('/api/moderation/users');
  const canRestrictions=['users_warn','users_mute','users_tempban','users_kick'].some(can);
  if(canRestrictions){for(const u of users){try{const r=await api(`/api/moderation/restrictions/${u.id}`);Object.assign(u,r)}catch{}}}
  renderUsers();
}
function renderUsers(){
  const q=$('member-search').value.trim().toLowerCase(),box=$('members-list');const xs=users.filter(u=>!u.is_bot&&u.id!==me.id&&u.username.toLowerCase().includes(q));
  box.innerHTML=xs.length?'':'<p class="muted">Aucun membre.</p>';
  xs.forEach(u=>{const c=document.createElement('article');c.className='member-card';c.innerHTML=`<div class="member-head"><div><strong>${esc(u.username)}</strong><div class="member-meta"><span>${esc(u.class_code||'Sans classe')}</span><span>${u.is_admin?'ADMIN':u.is_moderator?'MODO':'JOUEUR'}</span><span>⚠ ${u.warning_count||0}</span></div></div><span class="status-pill">${u.is_banned?'Banni':u.is_muted?'Muet jusqu’au '+esc(u.muted_until):'Actif'}</span></div><div class="actions"></div>`;const a=c.querySelector('.actions');
    if(can('users_warn'))a.append(button('Avertir','warn',()=>warn(u)));
    if(can('users_mute')){a.append(button('Mute','warn',()=>mute(u)));if(u.is_muted)a.append(button('Démute','good',()=>unmute(u)))}
    if(can('users_kick'))a.append(button('Expulser','',()=>kickMember112(u)));
    if(can('users_tempban'))a.append(button('Ban temporaire','danger',()=>tempBan(u)));
    if(can('notes_manage'))a.append(button('Notes','',()=>openNotes(u)));
    if(!a.children.length)a.innerHTML='<span class="muted">Consultation uniquement</span>';
    box.append(c)
  })
}
async function kickMember112(u){if(!confirm(`Expulser ${u.username} ? Le compte pourra se reconnecter.`))return;try{await api(`/api/admin/users/${u.id}/kick`,{method:'POST'});toast('Utilisateur expulsé.',true);await refreshAll()}catch(e){toast(e.message)}}
function renderReports(){const box=$('reports-list');box.innerHTML=reports.length?'':'<p class="muted">Aucun signalement dans cette vue.</p>';reports.forEach(r=>{const c=document.createElement('article');c.className='report-card';c.innerHTML=`<div class="report-head"><div><strong>${esc(r.author)}</strong> · ${esc(r.room_name)}</div><span class="status-pill">${esc(r.status)}</span></div><p class="meta">Signalé par ${esc(r.reporter)} — ${esc(r.created_at)} · ${esc(r.reason||'Sans motif')}</p><div class="report-message">${esc(r.content)}</div><div class="actions"></div>`;const a=c.querySelector('.actions');if(r.status==='open'){if(can('reports_resolve'))a.append(button('Résoudre','good',()=>decide(r,'resolved')),button('Rejeter','',()=>decide(r,'rejected')));if(can('messages_delete')&&can('reports_resolve'))a.append(button('Supprimer le message','danger',()=>deleteReported(r)));if(can('users_mute'))a.append(button('Sanctionner auteur','warn',()=>{const u=users.find(x=>x.id===r.author_id);if(u)mute(u)}))}box.append(c)})}
async function loadRooms(){if(!can('slowmode_manage'))return;rooms=await api('/api/rooms');renderRooms()}
async function loadActions(){if(!can('history_view'))return;actions=await api('/api/moderation/actions');const b=$('actions-body');b.innerHTML=actions.length?'':'<tr><td colspan="5">Aucune action.</td></tr>';actions.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(x.created_at)}</td><td>${esc(x.actor||'système')}</td><td>${esc(x.target||'—')}</td><td>${esc(x.action)}</td><td>${esc(x.reason||x.room_name||'')}</td>`;b.append(tr)})}
/* PiChat 1.1.3 — révision AutoModo par permission */
let moderatorAutomodIncidents112=[];
async function loadModeratorAutomod112(){
  if(!can('automod_review'))return;
  const state=$('moderation-automod-status')?.value||'open';
  moderatorAutomodIncidents112=await api(`/api/moderation/automod/incidents?status=${encodeURIComponent(state)}`);
  renderModeratorAutomod112();
}
function renderModeratorAutomod112(){
  const box=$('moderation-automod-list');if(!box)return;
  box.innerHTML=moderatorAutomodIncidents112.length?'':'<p class="muted">Aucun incident AutoModo dans cette vue.</p>';
  moderatorAutomodIncidents112.forEach(x=>{
    const card=document.createElement('article');card.className='report-card';
    card.innerHTML=`<div class="report-head"><div><strong>${esc(x.username)}</strong> · ${esc(x.room_name||'Salon')}</div><span class="status-pill">${esc(x.status)}</span></div><p class="meta">${esc(x.created_at)} · ${esc(x.rule)} · +${Number(x.points||0)} point(s)</p><div class="report-message">${esc(x.detail||x.content_preview||'Aucun détail')}</div><div class="actions"></div>`;
    const actions=card.querySelector('.actions');
    if(x.status==='open'){
      actions.append(button('Valider','good',()=>reviewModeratorAutomod112(x,'resolved')),button('Faux positif','',()=>reviewModeratorAutomod112(x,'ignored')),button('Reset points','warn',()=>resetModeratorAutomod112(x)));
    }
    box.append(card);
  });
}
async function reviewModeratorAutomod112(item,status){
  const note=prompt(status==='ignored'?'Pourquoi est-ce un faux positif ?':'Note de validation (facultative) :','');if(note===null)return;
  try{await post(`/api/moderation/automod/incidents/${item.id}`,{status,note});toast('Incident AutoModo mis à jour.',true);await loadModeratorAutomod112()}catch(e){toast(e.message)}
}
async function resetModeratorAutomod112(item){
  if(!confirm(`Remettre à zéro les points AutoModo de ${item.username} ?`))return;
  try{await post(`/api/moderation/automod/users/${item.user_id}/reset-points`,{});toast('Points AutoModo remis à zéro.',true);await loadModeratorAutomod112()}catch(e){toast(e.message)}
}
const applyPermissionUI1112=applyPermissionUI;
applyPermissionUI=function(){
  applyPermissionUI1112();
  showTabPermission('automod-review',can('automod_review'));
};
const refreshAll1112=refreshAll;
refreshAll=async function(){
  await refreshAll1112();
  if(can('automod_review')){try{await loadModeratorAutomod112()}catch(e){toast(e.message)}}
};
document.addEventListener('DOMContentLoaded',()=>{$('moderation-automod-status')?.addEventListener('change',()=>loadModeratorAutomod112().catch(e=>toast(e.message)))})
