(()=>{
'use strict';
const $=id=>document.getElementById(id), canvas=$('arena'), ctx=canvas.getContext('2d');
const picker=$('picker'), arenaWrap=$('arena-wrap'), list=$('fighter-list'), play=$('play');
let roster=[], selected=null, imgCache=new Map(), running=false, raf=0, last=0, fpsFrames=0, fpsAt=performance.now();
let world=null, input={up:false,down:false,left:false,right:false,mx:0,my:0,mouse:false,fire:false,super:false,joyX:0,joyY:0};
const W=1600,H=960,matchLength=90,goal=5;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}};
const rad=d=>d*Math.PI/180;

async function api(url){const r=await fetch(url,{credentials:'same-origin'});if(r.status===401){location.href='/login';throw new Error('Connexion requise')}if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Erreur'}))).detail||'Erreur');return r.json()}
function loadImage(url){if(imgCache.has(url))return imgCache.get(url);const im=new Image();im.src=url;imgCache.set(url,im);return im}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadRoster(){
  try{const data=await api('/api/pibrawl/roster');roster=data.fighters||[];if(!roster.length)throw new Error('Aucun combattant valide');renderRoster();}
  catch(e){list.innerHTML=`<div class="loading">⚠️ ${esc(e.message)}</div>`}
}
function renderRoster(){list.innerHTML=roster.map((f,i)=>`<button class="fighter-card" data-id="${esc(f.id)}" style="--fighter-color:${f.color}"><img class="fighter-head" src="${f.head_url}" alt=""><small>${esc(f.rarity)} · ${esc(f.title)}</small><h3>${esc(f.name)}</h3><p>${esc(f.description)}</p><div class="stats-mini"><span>❤️ ${f.stats.max_hp}</span><span>⚡ ${Math.round(f.stats.speed)}</span><span>💥 ${f.attack.pellets}×${f.attack.damage}</span></div></button>`).join('');list.querySelectorAll('.fighter-card').forEach(b=>b.onclick=()=>select(b.dataset.id));if(roster[0])select(roster[0].id)}
function select(id){selected=roster.find(x=>x.id===id);list.querySelectorAll('.fighter-card').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));play.disabled=!selected}

function makeFighter(cfg,x,y,team,bot=false,name=''){return{cfg,x,y,vx:0,vy:0,team,bot,name:name||cfg.name,hp:cfg.stats.max_hp,ammo:cfg.stats.ammo,ammoClock:0,lastShot:0,superHits:0,dead:0,kills:0,deaths:0,angle:0,flash:0,img:loadImage(cfg.head_url)}}
function resetWorld(){
  const cfg=selected;world={time:matchLength,scoreA:0,scoreB:0,projectiles:[],particles:[],walls:[{x:720,y:300,w:160,h:100},{x:720,y:560,w:160,h:100},{x:390,y:430,w:130,h:100},{x:1080,y:430,w:130,h:100}],fighters:[],ended:false};
  world.player=makeFighter(cfg,260,H/2,0,false,'Toi · '+cfg.name);world.fighters.push(world.player);
  const botCfg=cfg;
  world.fighters.push(makeFighter(botCfg,1320,260,1,true,'PiBot Alpha'),makeFighter(botCfg,1320,700,1,true,'PiBot Beta'),makeFighter(botCfg,1180,480,1,true,'PiBot Gamma'));
  resize();updateHud();
}
function circleRectCollide(c,r){const nx=clamp(c.x,r.x,r.x+r.w),ny=clamp(c.y,r.y,r.y+r.h);return Math.hypot(c.x-nx,c.y-ny)<c.cfg.stats.radius}
function moveEntity(f,dx,dy,dt){if(f.dead>0)return;let nx=clamp(f.x+dx*f.cfg.stats.speed*dt,45,W-45),ny=f.y;if(!world.walls.some(r=>circleRectCollide({...f,x:nx,y:ny},r)))f.x=nx;nx=f.x;ny=clamp(f.y+dy*f.cfg.stats.speed*dt,45,H-45);if(!world.walls.some(r=>circleRectCollide({...f,x:nx,y:ny},r)))f.y=ny}
function spawnShot(f,attack,angle,isSuper=false){const now=performance.now();if(now-f.lastShot<attack.cooldown_ms)return false;if(!isSuper&&f.ammo<=0)return false;if(isSuper&&f.superHits<attack.charge_hits)return false;f.lastShot=now;if(isSuper)f.superHits=0;else f.ammo--;const n=attack.pellets, spread=rad(attack.spread_deg);for(let i=0;i<n;i++){const t=n===1?0:(i/(n-1)-.5),a=angle+t*spread;world.projectiles.push({x:f.x+Math.cos(a)*(f.cfg.stats.radius+12),y:f.y+Math.sin(a)*(f.cfg.stats.radius+12),vx:Math.cos(a)*attack.projectile_speed,vy:Math.sin(a)*attack.projectile_speed,life:attack.range/attack.projectile_speed,damage:attack.damage,r:attack.projectile_radius,owner:f,team:f.team,knock:isSuper?(attack.knockback||0):0,color:isSuper?'#8f6cff':f.cfg.color})}f.flash=.09;return true}
function triggerSuper(f){const a=f.cfg.super;if(f.superHits<a.charge_hits)return false;if(a.type==='heal_pulse'){const now=performance.now();if(now-f.lastShot<a.cooldown_ms)return false;f.lastShot=now;f.superHits=0;f.hp=Math.min(f.cfg.stats.max_hp,f.hp+Math.round(f.cfg.stats.max_hp*.42));for(let i=0;i<18;i++)world.particles.push({x:f.x,y:f.y,vx:(Math.random()-.5)*240,vy:(Math.random()-.5)*240,life:.45,color:'#57f287'});return true}if(a.type==='dash_blast'){const d={x:Math.cos(f.angle),y:Math.sin(f.angle)};f.x=clamp(f.x+d.x*Math.max(90,a.knockback||160),45,W-45);f.y=clamp(f.y+d.y*Math.max(90,a.knockback||160),45,H-45)}return spawnShot(f,a,f.angle,true)}
function hitProjectile(p,target){target.hp-=p.damage;target.flash=.12;if(p.knock){const d=norm(target.x-p.owner.x,target.y-p.owner.y);target.x=clamp(target.x+d.x*p.knock,45,W-45);target.y=clamp(target.y+d.y*p.knock,45,H-45)}p.owner.superHits=Math.min(p.owner.cfg.super.charge_hits,p.owner.superHits+1);for(let i=0;i<6;i++)world.particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.25,color:p.color});if(target.hp<=0)kill(target,p.owner)}
function kill(target,killer){target.hp=0;target.dead=2.4;target.deaths++;killer.kills++;if(killer.team===0)world.scoreA++;else world.scoreB++;if(world.scoreA>=goal||world.scoreB>=goal)endMatch()}
function respawn(f){f.hp=f.cfg.stats.max_hp;f.ammo=f.cfg.stats.ammo;f.superHits=0;f.dead=0;if(f.team===0){f.x=240;f.y=H/2}else{f.x=1320;f.y=240+Math.random()*480}}
function nearestEnemy(f){let best=null,bd=1e9;for(const t of world.fighters){if(t.team===f.team||t.dead>0)continue;const d=dist(f,t);if(d<bd){bd=d;best=t}}return best}
function updateBot(f,dt){const t=nearestEnemy(f);if(!t)return;const dx=t.x-f.x,dy=t.y-f.y,d=Math.hypot(dx,dy),n=norm(dx,dy);f.angle=Math.atan2(dy,dx);let mx=n.x,my=n.y;if(d<300){mx=-n.x;my=-n.y}else if(d<520){mx=-n.y*.6;my=n.x*.6}moveEntity(f,mx,my,dt);if(d<f.cfg.attack.range*1.08&&Math.random()<dt*2.4)spawnShot(f,f.cfg.attack,f.angle,false);if(f.superHits>=f.cfg.super.charge_hits&&d<650&&Math.random()<dt*1.3)triggerSuper(f)}
function update(dt){if(!world||world.ended)return;world.time-=dt;if(world.time<=0)return endMatch();const p=world.player;if(p.dead>0){p.dead-=dt;if(p.dead<=0)respawn(p)}else{let dx=(input.right?1:0)-(input.left?1:0)+input.joyX,dy=(input.down?1:0)-(input.up?1:0)+input.joyY;if(dx||dy){const n=norm(dx,dy);moveEntity(p,n.x,n.y,dt)}const rect=canvas.getBoundingClientRect();if(input.mouse){const sx=canvas.width/rect.width,sy=canvas.height/rect.height;const wx=(input.mx*sx)/cameraScale()+cameraX(),wy=(input.my*sy)/cameraScale()+cameraY();p.angle=Math.atan2(wy-p.y,wx-p.x)}if(input.fire){spawnShot(p,p.cfg.attack,p.angle,false);input.fire=false}if(input.super){triggerSuper(p);input.super=false}}
  for(const f of world.fighters){if(f.bot){if(f.dead>0){f.dead-=dt;if(f.dead<=0)respawn(f)}else updateBot(f,dt)}if(f.flash>0)f.flash-=dt;if(f.dead<=0&&f.ammo<f.cfg.stats.ammo){f.ammoClock+=dt*1000;if(f.ammoClock>=f.cfg.stats.reload_ms){f.ammo++;f.ammoClock=0}}else if(f.ammo>=f.cfg.stats.ammo)f.ammoClock=0}
  for(const pr of world.projectiles){pr.x+=pr.vx*dt;pr.y+=pr.vy*dt;pr.life-=dt;for(const r of world.walls){if(pr.x>r.x&&pr.x<r.x+r.w&&pr.y>r.y&&pr.y<r.y+r.h)pr.life=0}if(pr.life>0){for(const f of world.fighters){if(f.team===pr.team||f.dead>0)continue;if(Math.hypot(f.x-pr.x,f.y-pr.y)<f.cfg.stats.radius+pr.r){hitProjectile(pr,f);pr.life=0;break}}}}
  world.projectiles=world.projectiles.filter(p=>p.life>0);for(const q of world.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}world.particles=world.particles.filter(q=>q.life>0);updateHud()}
function cameraScale(){return Math.min(canvas.width/(W*.78),canvas.height/(H*.78))}
function cameraX(){const s=cameraScale(),viewW=canvas.width/s;return clamp(world.player.x-viewW/2,0,W-viewW)}
function cameraY(){const s=cameraScale(),viewH=canvas.height/s;return clamp(world.player.y-viewH/2,0,H-viewH)}
function draw(){if(!world)return;ctx.clearRect(0,0,canvas.width,canvas.height);const s=cameraScale(),cx=cameraX(),cy=cameraY();ctx.save();ctx.scale(s,s);ctx.translate(-cx,-cy);ctx.fillStyle='#0b2634';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#143b4c';ctx.lineWidth=2;for(let x=0;x<W;x+=80){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=80){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#10384a';for(const r of world.walls){ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#2c657b';ctx.lineWidth=5;ctx.strokeRect(r.x,r.y,r.w,r.h)}for(const p of world.projectiles){ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const q of world.particles){ctx.globalAlpha=clamp(q.life/.25,0,1);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,4,4)}ctx.globalAlpha=1;for(const f of world.fighters)drawFighter(f);ctx.restore()}
function drawFighter(f){if(f.dead>0){ctx.globalAlpha=.22}const r=f.cfg.stats.radius;ctx.save();ctx.translate(f.x,f.y);ctx.rotate(f.angle);ctx.fillStyle=f.team===0?'#39d9ff':'#ff5473';ctx.globalAlpha=.22;ctx.beginPath();ctx.arc(0,0,r+8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=f.dead>0?.22:1;ctx.rotate(-f.angle);ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.clip();if(f.img.complete)ctx.drawImage(f.img,-r,-r,r*2,r*2);else{ctx.fillStyle=f.cfg.color;ctx.fillRect(-r,-r,r*2,r*2)}ctx.restore();ctx.globalAlpha=f.dead>0?.22:1;const hpw=72;ctx.fillStyle='#04111b';ctx.fillRect(f.x-hpw/2,f.y-r-21,hpw,8);ctx.fillStyle=f.team===0?'#48e784':'#ff5a71';ctx.fillRect(f.x-hpw/2,f.y-r-21,hpw*clamp(f.hp/f.cfg.stats.max_hp,0,1),8);ctx.fillStyle='#fff';ctx.font='700 13px system-ui';ctx.textAlign='center';ctx.fillText(f.name,f.x,f.y+r+22);ctx.globalAlpha=1}
function updateHud(){if(!world)return;const p=world.player;$('score-pill').textContent=`⭐ ${world.scoreA} — ${world.scoreB}`;$('timer').textContent=`${String(Math.floor(Math.max(0,world.time)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,world.time)%60)).padStart(2,'0')}`;$('hp').querySelector('i').style.width=`${clamp(p.hp/p.cfg.stats.max_hp,0,1)*100}%`;$('hp').querySelector('span').textContent=`${Math.max(0,Math.round(p.hp))} HP`;$('super-meter').querySelector('i').style.width=`${clamp(p.superHits/p.cfg.super.charge_hits,0,1)*100}%`;$('super-meter').querySelector('span').textContent=p.superHits>=p.cfg.super.charge_hits?'SUPER PRÊT':'SUPER';$('ammo').innerHTML=Array.from({length:p.cfg.stats.ammo},(_,i)=>`<i class="${i<p.ammo?'':'empty'}"></i>`).join('')}
function endMatch(){if(!world||world.ended)return;world.ended=true;const win=world.scoreA>world.scoreB;const box=$('result');box.hidden=false;box.innerHTML=`<div class="box"><h2>${win?'VICTOIRE 🏆':'FIN DE PARTIE'}</h2><p>Score ${world.scoreA} — ${world.scoreB}</p><p>${world.player.kills} éliminations · ${world.player.deaths} K.O.</p><button id="again">Rejouer</button></div>`;$('again').onclick=()=>{box.hidden=true;resetWorld()}}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000||.016);last=t;update(dt);draw();fpsFrames++;if(t-fpsAt>1000){$('fps-pill').textContent=`${Math.round(fpsFrames*1000/(t-fpsAt))} FPS`;fpsAt=t;fpsFrames=0}raf=requestAnimationFrame(loop)}
function start(){if(!selected)return;picker.hidden=true;arenaWrap.hidden=false;running=true;resetWorld();last=performance.now();raf=requestAnimationFrame(loop)}
function stop(){running=false;cancelAnimationFrame(raf);arenaWrap.hidden=true;picker.hidden=false;world=null}
function resize(){const r=arenaWrap.getBoundingClientRect();canvas.width=Math.max(640,Math.round(r.width*devicePixelRatio));canvas.height=Math.max(360,Math.round(r.height*devicePixelRatio))}
window.addEventListener('resize',resize);play.onclick=start;$('leave').onclick=stop;$('how').onclick=()=>$('help').showModal();document.querySelector('.close-help').onclick=()=>$('help').close();
const keyMap={KeyW:'up',KeyZ:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',KeyQ:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};window.addEventListener('keydown',e=>{if(keyMap[e.code]){input[keyMap[e.code]]=true;e.preventDefault()}if(e.code==='Space'){input.super=true;e.preventDefault()}});window.addEventListener('keyup',e=>{if(keyMap[e.code])input[keyMap[e.code]]=false});canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();input.mx=e.clientX-r.left;input.my=e.clientY-r.top;input.mouse=true});canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'){input.fire=true}});
// Mobile joystick
const zone=$('mobile-left'), knob=zone.querySelector('.stick i'), stick=zone.querySelector('.stick');let joyId=null;function joy(e){const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=44,d=Math.hypot(dx,dy)||1,k=Math.min(1,max/d);input.joyX=dx/max*k;input.joyY=dy/max*k;knob.style.transform=`translate(${input.joyX*max}px,${input.joyY*max}px)`}zone.addEventListener('pointerdown',e=>{joyId=e.pointerId;zone.setPointerCapture(e.pointerId);joy(e)});zone.addEventListener('pointermove',e=>{if(e.pointerId===joyId)joy(e)});const joyEnd=e=>{if(e.pointerId===joyId){joyId=null;input.joyX=input.joyY=0;knob.style.transform=''}};zone.addEventListener('pointerup',joyEnd);zone.addEventListener('pointercancel',joyEnd);
function aimNearest(){if(!world)return;const p=world.player,t=nearestEnemy(p);if(t)p.angle=Math.atan2(t.y-p.y,t.x-p.x)}$('mobile-fire').addEventListener('pointerdown',e=>{e.preventDefault();aimNearest();input.fire=true});$('mobile-super').addEventListener('pointerdown',e=>{e.preventDefault();aimNearest();input.super=true});
loadRoster();
})();
